security:
  oauth2:
    client:
      clientId: demo-management-ui
      clientSecret: CkZ+g6oqzR8=
      accessTokenUri: https://dev-auth.wernerds.net/core/connect/token
      userAuthorizationUri: https://dev-auth.wernerds.net/core/connect/authorize
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://dev-auth.wernerds.net/core/connect/userinfo