#server:
#  servlet:
#    context-path: /api/manage
#  port: 8762
#
#spring:
#    application:
#        name: management-service
#    devtools:
#        restart:
#            enabled: false
#        livereload:
#            enabled: false
#    jackson:
#        serialization.indent_output: true
#    datasource:
#        type: com.zaxxer.hikari.HikariDataSource
#        url: jdbc:mysql://localhost:3306/event?useUnicode=true&characterEncoding=utf8&useSSL=false&verifyServerCertificate=false
#        name:
#        username: root
#        password: intellijgentchart
#        hikari:
#            data-source-properties:
#                cachePrepStmts: true
#                prepStmtCacheSize: 250
#                prepStmtCacheSqlLimit: 2048
#                useServerPrepStmts: true
#    jpa:
#        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#        database: MYSQL
#        show-sql: false